[package]
name = "bflyt-rs"
authors = ["xhudaman"]
version = "0.1.0"
edition = "2021"
description = "A library for parsing and writing bflyt files."
license = "MIT"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
